version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: apt install python3-pip
      - run: pip3 install pipenv
      - run: pipenv install
      - run: python test_sum.py