version: 2
jobs:
  build:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Test Sum
          command: python test_sum.py
        - store_test_results:
            path: test-results
        - store_artifacts:
            path: test-results
            destination: tr1
  