version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
        name: update-npm
        command: "sudo npm install -g npm@latest"
      - run:
        name: jest-test
        command: npm test
      - store_test_results:
        path: test-results.xml

      
