version: 2
jobs:
  build:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;
      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Install pipenv and dependancies
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Test Sum
          command: python test_sum.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: artifacts
