version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Install Python
          command: sudo apt install python3-pip
      - run:
          name: Install pipenv
          command: sudo pip3 install pipenv
      - run:
          name: Install packages
          command: pipenv install
      - run:
          name: Test Sum
          command: python test_sum.py
