version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test-results:
    - node/test
    steps:
      - store_test_results:
        path: test-results.xml
workflows:
  node-tests:
    jobs:
      - test-results
