version: 2
jobs:
  build:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Build test-results dir
          command: |
            mkdir /tmp/test-results
            mkdir /tmp/artifacts
      - run:
          name: Install pipenv and dependancies
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Test Sum
          command: python test_sum.py
      - store_test_results:
          path: tpm/test-results
          destination: test-results
      - store_artifacts:
          path: tmp/artifacts
          destination: artifacts
